//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationControlBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRO()
        {
            this.REGISTRO_LIBRO = new HashSet<REGISTRO_LIBRO>();
        }
    
        public int id_libro { get; set; }
        public string nombre_libro { get; set; }
        public string autor { get; set; }
        public string editorial { get; set; }
        public Nullable<int> cantidad_disponible { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_LIBRO> REGISTRO_LIBRO { get; set; }
    }
}
