//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationControlBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_LIBRO
    {
        public int id { get; set; }
        public Nullable<int> id_libro { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<bool> multa { get; set; }
        public string observaciones { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual LIBRO LIBRO { get; set; }
    }
}
